buildscript {
    repositories {
        google()
        mavenCentral()
        maven {
            url "https://repo.huaweicloud.com/repository/maven/"
        }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.4'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            url "https://repo.huaweicloud.com/repository/maven/"
        }
    }
}
